from __future__ import annotations

"""ReAct orchestrator: Reasoning + Acting loop driven by the LLM.

Each iteration the LLM produces a (Pensamiento, Herramienta, Entrada) triple.
The system executes the tool and returns an Observation.  The loop continues
until the LLM calls 'responder' (answer ready) or 'rechazar' (no evidence),
or the iteration limit is reached.

Available tools
---------------
buscar(consulta)        Search the UNIR corpus for relevant chunks.
rechazar()              Refuse to answer — insufficient evidence.
redactar_correo(ctx)    Draft a formal email using the retrieved context.
responder()             Signal that enough evidence has been collected;
                        the final answer is then generated by the RAG prompt.
"""

import re
from typing import Callable, List

from assistant.llm.base import ChatMessage, LLMClient
from assistant.orchestrator.state import OrchestratorResult, ToolCall
from assistant.rag.retriever import RetrievedChunk
from assistant.tools.email_tool import EmailTool


RetrieveFn = Callable[[str, int, bool], List[RetrievedChunk]]
RerankFn = Callable[[str, List[RetrievedChunk]], List[RetrievedChunk]]
GenerateFn = Callable[[str, List[RetrievedChunk], str], tuple[str, dict[str, int]]]

_MAX_ITERATIONS = 5

_SYSTEM_PROMPT = """\
Eres un asistente universitario especializado en información de UNIR.
Respondes preguntas usando ÚNICAMENTE evidencia del corpus documental disponible.

Herramientas disponibles:
  buscar(consulta)       - Recupera fragmentos relevantes del corpus.
  rechazar()             - Indica que no hay evidencia suficiente para responder.
  redactar_correo(ctx)   - Genera un borrador de correo con el contexto indicado.
  responder()            - Señala que ya tienes evidencia suficiente para responder.

Formato obligatorio en CADA paso:
  Pensamiento: [razonamiento breve sobre qué hacer]
  Herramienta: [nombre_herramienta]
  Entrada: [argumento, o "ninguna" si no aplica]

Reglas:
  - Llama a "buscar" al menos UNA vez antes de "responder" o "rechazar".
  - Si la pregunta pide redactar un correo, llama a "redactar_correo".
  - Llama a "rechazar" si la búsqueda no devuelve evidencia útil.
  - Llama a "responder" cuando tengas evidencia suficiente.
  - Máximo {max_iter} pasos en total.
"""


def _parse_step(raw: str) -> tuple[str, str, str]:
    """Extract (thought, tool, tool_input) from a single LLM output block.

    Handles minor formatting variations from small models.
    """
    thought = ""
    tool = ""
    tool_input = ""

    for line in raw.splitlines():
        s = line.strip()
        low = s.lower()

        if low.startswith(("pensamiento:", "thought:", "razonamiento:")):
            thought = s.split(":", 1)[1].strip()

        elif low.startswith(("herramienta:", "acción:", "accion:", "action:", "tool:")):
            raw_tool = s.split(":", 1)[1].strip()
            # Strip trailing parentheses e.g. "buscar(consulta)" → "buscar"
            tool = re.split(r"[\s(]", raw_tool)[0].lower()

        elif low.startswith(("entrada:", "input:", "action input:", "argumento:")):
            tool_input = s.split(":", 1)[1].strip()

    # Fallback: if model ignored format, detect tool by keyword in full text
    if not tool:
        low_raw = raw.lower()
        for known in ("rechazar", "redactar_correo", "responder", "buscar"):
            if known in low_raw:
                tool = known
                break

    return thought, tool, tool_input


def _format_observation(chunks: List[RetrievedChunk]) -> str:
    if not chunks:
        return "No se encontraron fragmentos relevantes para esa consulta."
    parts = []
    for i, chunk in enumerate(chunks, start=1):
        excerpt = chunk.text[:350].replace("\n", " ")
        parts.append(f"[{i}] Fuente: {chunk.source}\n{excerpt}")
    return "\n\n".join(parts)


def _deduplicate(chunks: List[RetrievedChunk]) -> List[RetrievedChunk]:
    seen: set[tuple[str, int]] = set()
    out: List[RetrievedChunk] = []
    for c in chunks:
        key = (c.source, c.chunk_index)
        if key not in seen:
            seen.add(key)
            out.append(c)
    return out


class ReactOrchestrator:
    """LLM-driven ReAct loop for orchestrated RAG."""

    def __init__(
        self,
        retrieve: RetrieveFn,
        rerank: RerankFn,
        generate_answer: GenerateFn,
        min_score: float,
        llm_client: LLMClient,
        email_tool: EmailTool | None = None,
    ) -> None:
        self._retrieve = retrieve
        self._rerank = rerank
        self._generate_answer = generate_answer
        self._min_score = min_score
        self._llm = llm_client
        self._email_tool = email_tool or EmailTool()

    def run(
        self,
        question: str,
        *,
        top_k: int,
        use_reranking: bool,
        candidate_k: int,
    ) -> OrchestratorResult:
        messages: List[ChatMessage] = [
            ChatMessage(
                role="system",
                content=_SYSTEM_PROMPT.format(max_iter=_MAX_ITERATIONS),
            ),
            ChatMessage(role="user", content=f"Pregunta: {question}"),
        ]

        all_chunks: List[RetrievedChunk] = []
        tool_calls: List[ToolCall] = []
        token_usage: dict[str, int] = {"input_tokens": 0, "output_tokens": 0}
        email_draft = None

        for _ in range(_MAX_ITERATIONS):
            llm_response = self._llm.generate(
                messages,
                temperature=0.1,
                max_tokens=512,
            )
            token_usage["input_tokens"] += llm_response.input_tokens
            token_usage["output_tokens"] += llm_response.output_tokens

            thought, tool, tool_input = _parse_step(llm_response.content)
            messages.append(ChatMessage(role="assistant", content=llm_response.content))

            tc = ToolCall(
                tool_name=tool or "unknown",
                tool_input={"thought": thought, "input": tool_input},
                tool_output_summary=None,
            )
            tool_calls.append(tc)

            # ── responder ───────────────────────────────────────────────────
            if tool == "responder":
                tc.tool_output_summary = "ready to answer"
                answer, gen_usage = self._generate_answer(question, all_chunks, "direct")
                token_usage["input_tokens"] += gen_usage.get("input_tokens", 0)
                token_usage["output_tokens"] += gen_usage.get("output_tokens", 0)
                return OrchestratorResult(
                    question=question,
                    plan=None,
                    retrieved_chunks=all_chunks,
                    final_chunks=all_chunks,
                    answer=answer,
                    refused=False,
                    evidence_sufficient=True,
                    token_usage=token_usage,
                    email_draft=email_draft,
                    tool_calls=tool_calls,
                )

            # ── rechazar ────────────────────────────────────────────────────
            if tool == "rechazar":
                tc.tool_output_summary = "refused"
                return OrchestratorResult(
                    question=question,
                    plan=None,
                    retrieved_chunks=all_chunks,
                    final_chunks=[],
                    answer=(
                        "No dispongo de información suficiente en el corpus "
                        "para responder a esta pregunta."
                    ),
                    refused=True,
                    evidence_sufficient=False,
                    token_usage=token_usage,
                    email_draft=None,
                    tool_calls=tool_calls,
                )

            # ── buscar ──────────────────────────────────────────────────────
            if tool == "buscar":
                query = tool_input if tool_input and tool_input.lower() not in (
                    "ninguna", "none", ""
                ) else question
                fetch_k = candidate_k if use_reranking else top_k
                chunks = self._retrieve(query, fetch_k, use_reranking)
                if use_reranking and chunks:
                    chunks = self._rerank(query, chunks, top_k=top_k)
                all_chunks = _deduplicate(all_chunks + chunks)
                observation = _format_observation(chunks)
                tc.tool_output_summary = f"{len(chunks)} chunks retrieved"
                messages.append(
                    ChatMessage(role="user", content=f"Observación:\n{observation}")
                )
                continue

            # ── redactar_correo ─────────────────────────────────────────────
            if tool == "redactar_correo":
                from assistant.orchestrator.evidence import build_context_summary
                context = tool_input if tool_input and tool_input.lower() not in (
                    "ninguna", "none", ""
                ) else build_context_summary(all_chunks)
                email_draft = self._email_tool.draft_email(
                    user_request=question,
                    supporting_context=context,
                )
                observation = f"Borrador listo. Asunto: {email_draft.subject}"
                tc.tool_output_summary = "email draft created"
                messages.append(
                    ChatMessage(role="user", content=f"Observación: {observation}")
                )
                # After drafting the email we still let the loop call "responder"
                continue

            # ── unknown / malformed ─────────────────────────────────────────
            observation = (
                f"Herramienta '{tool}' no reconocida. "
                "Usa: buscar, rechazar, redactar_correo, responder."
            )
            tc.tool_output_summary = "unknown tool"
            messages.append(
                ChatMessage(role="user", content=f"Observación: {observation}")
            )

        # Max iterations reached — fall back to generating from collected chunks
        tc_fallback = ToolCall(
            tool_name="fallback_answer",
            tool_input={},
            tool_output_summary="max iterations reached",
        )
        tool_calls.append(tc_fallback)

        if all_chunks:
            answer, gen_usage = self._generate_answer(question, all_chunks, "direct")
            token_usage["input_tokens"] += gen_usage.get("input_tokens", 0)
            token_usage["output_tokens"] += gen_usage.get("output_tokens", 0)
            refused = False
            evidence_sufficient = True
        else:
            answer = (
                "No dispongo de información suficiente en el corpus "
                "para responder a esta pregunta."
            )
            refused = True
            evidence_sufficient = False

        return OrchestratorResult(
            question=question,
            plan=None,
            retrieved_chunks=all_chunks,
            final_chunks=all_chunks if not refused else [],
            answer=answer,
            refused=refused,
            evidence_sufficient=evidence_sufficient,
            token_usage=token_usage,
            email_draft=email_draft,
            tool_calls=tool_calls,
        )
